INFO 2019-12-13 13:46:32,208 basehttp 124 "GET /index/ HTTP/1.1" 200 18
INFO 2019-12-13 13:46:32,961 basehttp 124 "GET /index/ HTTP/1.1" 200 18
INFO 2019-12-13 14:11:08,974 basehttp 124 "GET /user/index HTTP/1.1" 301 0
INFO 2019-12-13 14:11:08,983 basehttp 124 "GET /user/index/ HTTP/1.1" 200 2
ERROR 2019-12-13 17:04:45,037 exception 135 Internal Server Error: /management/user/login
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\utils\deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "F:\Env\django_env\lib\site-packages\django\middleware\common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "F:\Env\django_env\lib\site-packages\django\middleware\common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:5000/management/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2019-12-13 17:04:45,165 basehttp 124 "POST /management/user/login HTTP/1.1" 500 68373
WARNING 2019-12-13 17:04:56,945 csrf 160 Forbidden (CSRF cookie not set.): /management/user/login/
WARNING 2019-12-13 17:04:56,971 basehttp 124 "POST /management/user/login/ HTTP/1.1" 403 2829
ERROR 2019-12-13 17:05:28,045 exception 135 Internal Server Error: /management/user/login/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2019-12-13 17:05:28,155 basehttp 124 "POST /management/user/login/ HTTP/1.1" 500 65004
ERROR 2019-12-13 17:06:02,308 exception 135 Internal Server Error: /management/user/login/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: post() takes 1 positional argument but 2 were given
ERROR 2019-12-13 17:06:02,413 basehttp 124 "POST /management/user/login/ HTTP/1.1" 500 73925
INFO 2019-12-13 17:06:36,101 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 46
INFO 2019-12-13 17:08:09,464 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 46
INFO 2019-12-13 17:08:40,209 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 46
INFO 2019-12-13 17:09:42,712 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 46
INFO 2019-12-13 17:10:33,608 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 32
INFO 2019-12-13 17:11:22,329 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 32
INFO 2019-12-13 17:12:38,253 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 40
INFO 2019-12-13 17:13:07,654 basehttp 124 "POST /management/user/login/ HTTP/1.1" 200 40
INFO 2019-12-13 21:06:59,202 basehttp 124 "GET /management/users HTTP/1.1" 301 0
ERROR 2019-12-13 21:06:59,209 exception 135 Internal Server Error: /management/users/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\management\user\views.py", line 48, in get
    filters.append(User.eamil == email)
AttributeError: type object 'User' has no attribute 'eamil'
ERROR 2019-12-13 21:06:59,687 basehttp 124 "GET /management/users/ HTTP/1.1" 500 82166
WARNING 2019-12-13 21:07:00,090 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 21:07:00,091 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2315
INFO 2019-12-13 21:07:17,873 basehttp 124 "GET /management/users/ HTTP/1.1" 200 32
INFO 2019-12-13 21:17:30,640 basehttp 124 "GET /online/login HTTP/1.1" 301 0
INFO 2019-12-13 21:17:30,925 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6754
WARNING 2019-12-13 21:17:30,974 base 152 Not Found: /online/static/src/assets/images/icon.png
WARNING 2019-12-13 21:17:30,984 base 152 Not Found: /online/static/src/assets/javascript/common/base.js
WARNING 2019-12-13 21:17:30,979 base 152 Not Found: /online/static/src/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-13 21:17:30,988 base 152 Not Found: /online/static/src/assets/images/banner.png
WARNING 2019-12-13 21:17:30,989 basehttp 124 "GET /online/static/src/assets/images/icon.png HTTP/1.1" 404 2564
WARNING 2019-12-13 21:17:30,990 basehttp 124 "GET /online/static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 2612
WARNING 2019-12-13 21:17:30,990 basehttp 124 "GET /online/static/src/assets/javascript/common/base.js HTTP/1.1" 404 2594
WARNING 2019-12-13 21:17:30,995 base 152 Not Found: /online/static/src/assets/javascript/common/header.js
WARNING 2019-12-13 21:17:30,995 basehttp 124 "GET /online/static/src/assets/images/banner.png HTTP/1.1" 404 2570
WARNING 2019-12-13 21:17:31,000 base 152 Not Found: /online/static/src/assets/javascript/common/common.js
INFO 2019-12-13 21:17:31,000 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
WARNING 2019-12-13 21:17:31,005 base 152 Not Found: /online/static/src/assets/javascript/page/index.js
WARNING 2019-12-13 21:17:31,006 basehttp 124 "GET /online/static/src/assets/javascript/common/header.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:31,010 base 152 Not Found: /online/static/src/assets/images/thing.png
WARNING 2019-12-13 21:17:31,013 base 152 Not Found: /online/static/src/assets/javascript/common/base.js
WARNING 2019-12-13 21:17:31,014 basehttp 124 "GET /online/static/src/assets/javascript/page/index.js HTTP/1.1" 404 2591
WARNING 2019-12-13 21:17:31,014 basehttp 124 "GET /online/static/src/assets/javascript/common/common.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:31,016 basehttp 124 "GET /online/static/src/assets/images/thing.png HTTP/1.1" 404 2567
WARNING 2019-12-13 21:17:31,016 basehttp 124 "GET /online/static/src/assets/javascript/common/base.js HTTP/1.1" 404 2594
WARNING 2019-12-13 21:17:31,088 base 152 Not Found: /online/static/src/assets/javascript/common/header.js
WARNING 2019-12-13 21:17:31,089 basehttp 124 "GET /online/static/src/assets/javascript/common/header.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:31,097 base 152 Not Found: /online/static/src/assets/javascript/common/common.js
WARNING 2019-12-13 21:17:31,100 basehttp 124 "GET /online/static/src/assets/javascript/common/common.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:31,107 base 152 Not Found: /online/static/src/assets/javascript/page/index.js
WARNING 2019-12-13 21:17:31,107 basehttp 124 "GET /online/static/src/assets/javascript/page/index.js HTTP/1.1" 404 2591
INFO 2019-12-13 21:17:40,966 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6754
WARNING 2019-12-13 21:17:40,995 base 152 Not Found: /online/static/src/assets/images/icon.png
WARNING 2019-12-13 21:17:40,995 basehttp 124 "GET /online/static/src/assets/images/icon.png HTTP/1.1" 404 2564
WARNING 2019-12-13 21:17:41,008 base 152 Not Found: /online/static/src/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-13 21:17:41,013 base 152 Not Found: /online/static/src/assets/javascript/common/base.js
WARNING 2019-12-13 21:17:41,021 base 152 Not Found: /online/static/src/assets/images/banner.png
WARNING 2019-12-13 21:17:41,021 basehttp 124 "GET /online/static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 2612
WARNING 2019-12-13 21:17:41,029 base 152 Not Found: /online/static/src/assets/javascript/common/header.js
WARNING 2019-12-13 21:17:41,031 basehttp 124 "GET /online/static/src/assets/javascript/common/base.js HTTP/1.1" 404 2594
WARNING 2019-12-13 21:17:41,037 base 152 Not Found: /online/static/src/assets/javascript/common/common.js
WARNING 2019-12-13 21:17:41,037 basehttp 124 "GET /online/static/src/assets/images/banner.png HTTP/1.1" 404 2570
WARNING 2019-12-13 21:17:41,041 base 152 Not Found: /online/static/src/assets/javascript/page/index.js
WARNING 2019-12-13 21:17:41,043 basehttp 124 "GET /online/static/src/assets/javascript/common/header.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:41,051 base 152 Not Found: /online/static/src/assets/images/thing.png
WARNING 2019-12-13 21:17:41,051 basehttp 124 "GET /online/static/src/assets/javascript/common/common.js HTTP/1.1" 404 2600
WARNING 2019-12-13 21:17:41,053 basehttp 124 "GET /online/static/src/assets/javascript/page/index.js HTTP/1.1" 404 2591
WARNING 2019-12-13 21:17:41,057 basehttp 124 "GET /online/static/src/assets/images/thing.png HTTP/1.1" 404 2567
INFO 2019-12-13 21:23:39,425 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6729
INFO 2019-12-13 21:23:39,488 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 21:23:39,501 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 21:23:39,505 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-13 21:23:39,523 base 152 Not Found: /online/static/src/assets/images/thing.png
WARNING 2019-12-13 21:23:39,530 basehttp 124 "GET /online/static/src/assets/images/thing.png HTTP/1.1" 404 2567
INFO 2019-12-13 21:23:39,533 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 21:23:39,542 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 21:23:39,561 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
INFO 2019-12-13 21:23:39,659 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
WARNING 2019-12-13 21:23:39,660 basehttp 124 "GET /static/src/assets/javascript/page/index.j HTTP/1.1" 404 1715
INFO 2019-12-13 21:23:51,270 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6729
WARNING 2019-12-13 21:23:51,298 base 152 Not Found: /online/static/src/assets/images/thing.png
WARNING 2019-12-13 21:23:51,305 basehttp 124 "GET /online/static/src/assets/images/thing.png HTTP/1.1" 404 2567
WARNING 2019-12-13 21:23:51,306 basehttp 124 "GET /static/src/assets/javascript/page/index.j HTTP/1.1" 404 1715
INFO 2019-12-13 21:24:26,600 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6728
INFO 2019-12-13 21:24:26,641 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 21:24:30,380 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6728
INFO 2019-12-13 21:24:30,406 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 21:24:30,415 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 21:24:30,421 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 21:24:30,422 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 21:24:30,425 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 21:24:30,430 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 21:24:30,434 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 21:24:30,440 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 21:24:30,460 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 21:24:30,512 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 21:24:30,514 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 21:24:59,615 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6728
INFO 2019-12-13 21:24:59,644 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 21:24:59,651 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 21:24:59,664 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 21:24:59,665 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 21:24:59,669 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 21:24:59,677 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 21:24:59,670 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 21:24:59,681 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 21:24:59,706 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 21:24:59,760 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 21:24:59,761 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
ERROR 2019-12-13 22:15:32,440 exception 135 Internal Server Error: /online/login/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 12, in login
    category[category.id] = {"name":category.name,"sub_cats":[]}
TypeError: 'Category' object does not support item assignment
ERROR 2019-12-13 22:15:32,554 basehttp 124 "GET /online/login/ HTTP/1.1" 500 72902
ERROR 2019-12-13 22:16:33,698 exception 135 Internal Server Error: /online/login/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 12, in login
    category[category.id] = {"name":category.name,"sub_cats":[]}
TypeError: 'Category' object does not support item assignment
ERROR 2019-12-13 22:16:33,807 basehttp 124 "GET /online/login/ HTTP/1.1" 500 72872
ERROR 2019-12-13 22:17:32,659 exception 135 Internal Server Error: /online/login/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 12, in login
    category[cate.id] = {"name":category.name,"sub_cats":[]}
AttributeError: 'dict' object has no attribute 'name'
ERROR 2019-12-13 22:17:32,752 basehttp 124 "GET /online/login/ HTTP/1.1" 500 73008
INFO 2019-12-13 22:17:58,920 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6723
INFO 2019-12-13 22:18:22,684 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6723
INFO 2019-12-13 22:20:47,394 basehttp 124 "GET /online/login/ HTTP/1.1" 200 6723
INFO 2019-12-13 22:27:52,392 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:27:58,380 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:27:58,405 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:27:58,411 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:27:58,412 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:27:58,413 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:27:58,415 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:27:58,415 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:27:58,424 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:27:58,434 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:27:58,463 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:27:58,486 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:27:58,487 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:30:09,126 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:30:09,159 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:30:09,164 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:30:09,164 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:30:09,167 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:30:09,169 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:30:09,169 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:30:09,171 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:30:09,180 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:30:09,202 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:30:09,229 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:30:09,230 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:30:09,886 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:30:09,917 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:30:09,919 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:30:09,925 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:30:09,926 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:30:09,927 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:30:09,931 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:30:09,937 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:30:09,942 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:30:09,967 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:30:09,986 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:30:09,986 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:30:10,537 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:30:10,559 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:30:10,565 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:30:10,569 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:30:10,569 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:30:10,576 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:30:10,583 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:30:10,584 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:30:10,587 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:30:10,609 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:30:10,636 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:30:10,637 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:30:11,068 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:30:11,090 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:30:11,092 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:30:11,098 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:30:11,099 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:30:11,104 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:30:11,105 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:30:11,105 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:30:11,111 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:30:11,135 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:30:11,157 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:30:11,158 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:33:45,641 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4718
INFO 2019-12-13 22:33:45,668 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:33:45,688 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:33:45,689 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:33:45,690 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:33:45,693 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:33:45,695 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:33:45,727 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:33:45,727 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:33:45,741 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:33:45,802 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:33:45,803 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:34:41,314 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4491
INFO 2019-12-13 22:34:41,341 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:34:41,352 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:34:41,352 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:34:41,357 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:34:41,358 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:34:41,359 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:34:41,382 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:34:41,383 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:34:41,409 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:34:41,469 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:34:41,470 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:34:45,548 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4491
INFO 2019-12-13 22:34:45,577 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:34:45,580 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:34:45,588 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:34:45,591 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:34:45,592 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:34:45,593 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:34:45,596 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:34:45,615 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:34:45,634 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:34:45,681 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:34:45,681 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:35:56,011 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4491
INFO 2019-12-13 22:35:56,043 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:35:56,056 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:35:56,062 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:35:56,067 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:35:56,069 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:35:56,070 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:35:56,089 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:35:56,094 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:35:56,119 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:35:56,167 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:35:56,168 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:35:59,400 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4491
INFO 2019-12-13 22:35:59,432 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:35:59,433 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:35:59,435 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:35:59,439 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:35:59,443 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:35:59,445 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:35:59,448 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:35:59,462 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:35:59,494 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:35:59,537 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:35:59,538 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
ERROR 2019-12-13 22:38:05,231 exception 135 Internal Server Error: /online/login/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 15, in login
    category[sub_cate.super_category.id]["sub_cats"].append({"id":sub_cate.id,"name":sub_cate.name})
IndexError: list index out of range
ERROR 2019-12-13 22:38:05,328 basehttp 124 "GET /online/login/ HTTP/1.1" 500 73148
WARNING 2019-12-13 22:38:05,434 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:38:05,435 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:44:28,079 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4505
INFO 2019-12-13 22:44:28,133 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:44:28,134 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:44:28,134 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:44:28,137 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:44:28,151 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:44:28,155 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:44:28,156 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:44:28,304 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:44:28,343 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:44:28,366 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:44:28,367 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:45:16,520 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:45:16,551 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:45:16,554 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:45:16,555 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:45:16,555 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:45:16,556 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:45:16,559 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:45:16,571 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:45:16,573 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:45:16,761 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:45:16,776 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:45:16,779 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:45:17,961 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:45:17,983 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:45:17,989 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:45:17,993 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:45:17,998 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:45:17,998 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:45:17,998 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:45:18,000 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:45:18,009 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:45:18,037 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:45:18,055 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:45:18,055 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:46:07,276 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:46:07,303 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:46:07,311 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:46:07,312 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:46:07,312 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:46:07,313 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:46:07,316 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:46:07,328 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:46:07,329 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:46:07,356 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:46:07,382 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:46:07,383 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:46:08,076 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4372
INFO 2019-12-13 22:46:08,100 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:46:08,102 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:46:08,105 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:46:08,108 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:46:08,110 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:46:08,112 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:46:08,112 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:46:08,121 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:46:08,146 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:46:08,173 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:46:08,173 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:46:23,228 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4754
INFO 2019-12-13 22:46:23,252 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:46:23,259 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:46:23,262 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:46:23,263 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:46:23,264 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:46:23,267 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:46:23,278 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:46:23,279 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:46:23,484 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:46:23,500 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:46:23,501 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:46:40,060 basehttp 124 "GET /online/login/ HTTP/1.1" 200 4994
INFO 2019-12-13 22:46:40,084 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:46:40,099 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:46:40,103 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:46:40,104 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:46:40,107 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:46:40,107 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:46:40,110 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:46:40,121 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:46:40,141 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:46:40,169 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:46:40,170 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:47:39,186 basehttp 124 "GET /online/login/ HTTP/1.1" 200 5502
INFO 2019-12-13 22:47:39,224 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:47:39,229 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:47:39,232 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:47:39,235 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:47:39,236 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:47:39,237 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:47:39,262 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:47:39,267 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:47:39,291 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:47:39,350 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:47:39,351 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
INFO 2019-12-13 22:48:36,559 basehttp 124 "GET /online/login/ HTTP/1.1" 200 5490
INFO 2019-12-13 22:48:36,584 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-13 22:48:36,594 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-13 22:48:36,598 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-13 22:48:36,601 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-13 22:48:36,605 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-13 22:48:36,607 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-13 22:48:36,625 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-13 22:48:36,627 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-13 22:48:36,806 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-13 22:48:36,826 base 152 Not Found: /favicon.ico
WARNING 2019-12-13 22:48:36,828 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
WARNING 2019-12-14 09:03:09,244 base 152 Not Found: /index/
WARNING 2019-12-14 09:03:09,246 basehttp 124 "GET /index/ HTTP/1.1" 404 2408
WARNING 2019-12-14 09:03:09,424 base 152 Not Found: /favicon.ico
WARNING 2019-12-14 09:03:09,425 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2423
WARNING 2019-12-14 09:03:12,630 base 152 Not Found: /
WARNING 2019-12-14 09:03:12,631 basehttp 124 "GET / HTTP/1.1" 404 2372
WARNING 2019-12-14 09:03:56,733 base 152 Not Found: /
WARNING 2019-12-14 09:03:56,735 basehttp 124 "GET / HTTP/1.1" 404 2479
WARNING 2019-12-14 09:04:05,514 base 152 Not Found: /online
WARNING 2019-12-14 09:04:05,515 basehttp 124 "GET /online HTTP/1.1" 404 2515
INFO 2019-12-14 09:05:00,339 basehttp 124 "GET /online HTTP/1.1" 301 0
ERROR 2019-12-14 09:05:00,579 exception 135 Internal Server Error: /online/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 8, in index
    cates = Category.objects.filter(super_category__isnull = True)
NameError: name 'Category' is not defined
ERROR 2019-12-14 09:05:00,756 basehttp 124 "GET /online/ HTTP/1.1" 500 69150
INFO 2019-12-14 09:05:55,497 basehttp 124 "GET /online/ HTTP/1.1" 200 4372
INFO 2019-12-14 09:05:55,550 basehttp 124 "GET /static/src/assets/css/page/index.css HTTP/1.1" 200 10387
INFO 2019-12-14 09:05:55,550 basehttp 124 "GET /static/src/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-14 09:05:55,558 basehttp 124 "GET /static/src/assets/javascript/common/base.js HTTP/1.1" 200 764
INFO 2019-12-14 09:05:55,558 basehttp 124 "GET /static/src/assets/javascript/common/header.js HTTP/1.1" 200 1054
INFO 2019-12-14 09:05:55,559 basehttp 124 "GET /static/src/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-14 09:05:55,587 basehttp 124 "GET /static/src/assets/javascript/common/common.js HTTP/1.1" 200 192
INFO 2019-12-14 09:05:55,587 basehttp 124 "GET /static/src/assets/javascript/page/index.js HTTP/1.1" 200 401
INFO 2019-12-14 09:05:55,604 basehttp 124 "GET /static/src/assets/images/thing.png HTTP/1.1" 200 148959
INFO 2019-12-14 09:05:55,630 basehttp 124 "GET /static/src/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-14 09:06:26,981 base 152 Not Found: /online/index
WARNING 2019-12-14 09:06:26,984 basehttp 124 "GET /online/index HTTP/1.1" 404 2475
INFO 2019-12-14 09:06:30,374 basehttp 124 "GET /online/ HTTP/1.1" 200 4372
ERROR 2019-12-14 14:25:35,705 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 45, in get
    user = User.objects.get(user_id)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 370, in get
    clone = self.filter(*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 781, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 799, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1260, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1286, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1161, in build_filter
    arg, value = filter_expr
TypeError: 'int' object is not iterable
ERROR 2019-12-14 14:25:36,160 basehttp 124 "GET /online/user/ HTTP/1.1" 500 112285
ERROR 2019-12-14 14:27:38,549 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 45, in get
    user = User.objects.get(user_id)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 370, in get
    clone = self.filter(*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 781, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 799, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1260, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1286, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1161, in build_filter
    arg, value = filter_expr
TypeError: 'int' object is not iterable
ERROR 2019-12-14 14:27:38,770 basehttp 124 "GET /online/user/ HTTP/1.1" 500 113993
ERROR 2019-12-14 14:28:06,678 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 50, in get
    context = {"email":user.eami,"phone":user.phone,"password":user.password,
AttributeError: 'User' object has no attribute 'eami'
ERROR 2019-12-14 14:28:06,837 basehttp 124 "GET /online/user/ HTTP/1.1" 500 83849
ERROR 2019-12-14 14:28:26,757 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 52, in get
    "road":useraddress.road,"district":useraddress.district,
AttributeError: 'RelatedManager' object has no attribute 'road'
ERROR 2019-12-14 14:28:26,935 basehttp 124 "GET /online/user/ HTTP/1.1" 500 83748
ERROR 2019-12-14 14:34:59,259 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 49, in get
    useraddress = user.address[0]
TypeError: 'RelatedManager' object does not support indexing
ERROR 2019-12-14 14:34:59,424 basehttp 124 "GET /online/user/ HTTP/1.1" 500 83448
INFO 2019-12-14 14:35:20,365 basehttp 124 "GET /online/user/ HTTP/1.1" 200 273
ERROR 2019-12-14 14:35:58,111 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 49, in get
    useraddress = user.address.all()[0].values()
AttributeError: 'UserAddress' object has no attribute 'values'
ERROR 2019-12-14 14:35:58,197 basehttp 124 "GET /online/user/ HTTP/1.1" 500 81348
ERROR 2019-12-14 14:35:59,690 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 49, in get
    useraddress = user.address.all()[0].values()
AttributeError: 'UserAddress' object has no attribute 'values'
ERROR 2019-12-14 14:35:59,727 basehttp 124 "GET /online/user/ HTTP/1.1" 500 81348
ERROR 2019-12-14 14:36:18,813 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 53, in get
    "road":useraddress.road,"district":useraddress.district,
AttributeError: 'QuerySet' object has no attribute 'road'
ERROR 2019-12-14 14:36:18,903 basehttp 124 "GET /online/user/ HTTP/1.1" 500 81710
ERROR 2019-12-14 14:36:20,569 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 53, in get
    "road":useraddress.road,"district":useraddress.district,
AttributeError: 'QuerySet' object has no attribute 'road'
ERROR 2019-12-14 14:36:20,604 basehttp 124 "GET /online/user/ HTTP/1.1" 500 81710
ERROR 2019-12-14 14:38:37,878 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 53, in get
    "road":useraddress.road,"district":useraddress.district,
AttributeError: 'list' object has no attribute 'road'
ERROR 2019-12-14 14:38:37,968 basehttp 124 "GET /online/user/ HTTP/1.1" 500 81699
INFO 2019-12-14 14:42:08,935 basehttp 124 "GET /online/user/ HTTP/1.1" 200 303
INFO 2019-12-14 14:42:48,980 basehttp 124 "GET /online/user/ HTTP/1.1" 200 293
INFO 2019-12-14 14:58:52,565 basehttp 124 "GET /online/user/ HTTP/1.1" 200 44
INFO 2019-12-14 14:59:20,020 basehttp 124 "GET /online/user/ HTTP/1.1" 200 293
ERROR 2019-12-14 15:18:03,193 exception 135 Internal Server Error: /online/user/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\login\views.py", line 49, in get
    return JsonResponse(context)
  File "D:\python_virtual\django_env\lib\site-packages\django\http\response.py", line 524, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2019-12-14 15:18:03,301 basehttp 124 "GET /online/user/ HTTP/1.1" 500 99763
INFO 2019-12-14 15:19:19,571 basehttp 124 "GET /online/user/ HTTP/1.1" 200 4
INFO 2019-12-14 15:19:22,195 basehttp 124 "GET /online/user/ HTTP/1.1" 200 4
INFO 2019-12-14 15:21:10,101 basehttp 124 "GET /online/user/ HTTP/1.1" 200 4
INFO 2019-12-14 15:21:42,258 basehttp 124 "GET /online/user/ HTTP/1.1" 200 4
INFO 2019-12-14 15:22:33,101 basehttp 124 "GET /online/user/ HTTP/1.1" 200 242
INFO 2019-12-14 15:26:22,472 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 52
INFO 2019-12-14 15:27:13,816 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 52
INFO 2019-12-14 15:27:46,752 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:35:11,145 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:37:22,777 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:38:51,847 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:38:58,401 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:40:03,615 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:40:37,926 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:42:59,300 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 40
INFO 2019-12-14 15:43:11,047 basehttp 124 "PUT /online/user/ HTTP/1.1" 200 42
INFO 2019-12-14 15:49:52,876 basehttp 124 "GET /online/user/ HTTP/1.1" 200 298
WARNING 2019-12-14 16:18:37,092 base 152 Not Found: /online/goods/1/detail/
WARNING 2019-12-14 16:18:37,094 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 404 3704
ERROR 2019-12-14 16:19:16,233 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 117, in get
    context = single_goods.values("name_en","image","price","sale","detail_en","description_en")
AttributeError: 'Goods' object has no attribute 'values'
ERROR 2019-12-14 16:19:16,320 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 81236
ERROR 2019-12-14 16:21:20,686 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1655, in add_fields
    name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1427, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1362, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'detail_en' into field. Choices are: added_time, cart_goods, category, category_id, description_ch, description_en, detail_ch, detail_zh, id, image, is_hot, name_ch, name_en, on_sale, order_goods, price, sale, stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 116, in get
    context = single_goods.values("name_en","image","price","sale","detail_en","description_en")
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 694, in values
    clone = self._values(*fields, **expressions)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 689, in _values
    clone.query.set_values(fields)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1906, in set_values
    self.add_fields(field_names, True)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1669, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'detail_en' into field. Choices are: added_time, cart_goods, category, category_id, description_ch, description_en, detail_ch, detail_zh, id, image, is_hot, name_ch, name_en, on_sale, order_goods, price, sale, stock
ERROR 2019-12-14 16:21:20,813 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 120280
ERROR 2019-12-14 16:21:21,131 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1655, in add_fields
    name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1427, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1362, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'detail_en' into field. Choices are: added_time, cart_goods, category, category_id, description_ch, description_en, detail_ch, detail_zh, id, image, is_hot, name_ch, name_en, on_sale, order_goods, price, sale, stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 116, in get
    context = single_goods.values("name_en","image","price","sale","detail_en","description_en")
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 694, in values
    clone = self._values(*fields, **expressions)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\query.py", line 689, in _values
    clone.query.set_values(fields)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1906, in set_values
    self.add_fields(field_names, True)
  File "D:\python_virtual\django_env\lib\site-packages\django\db\models\sql\query.py", line 1669, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'detail_en' into field. Choices are: added_time, cart_goods, category, category_id, description_ch, description_en, detail_ch, detail_zh, id, image, is_hot, name_ch, name_en, on_sale, order_goods, price, sale, stock
ERROR 2019-12-14 16:21:21,215 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 120280
ERROR 2019-12-14 16:22:05,155 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 117, in get
    return JsonResponse(context)
  File "D:\python_virtual\django_env\lib\site-packages\django\http\response.py", line 524, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2019-12-14 16:22:05,272 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 86607
ERROR 2019-12-14 16:22:21,137 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 117, in get
    return JsonResponse(context,safe=False)
  File "D:\python_virtual\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'QuerySet' is not JSON serializable
ERROR 2019-12-14 16:22:21,375 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 107847
INFO 2019-12-14 16:22:43,108 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 130
INFO 2019-12-14 16:23:20,904 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 130
ERROR 2019-12-14 16:25:45,511 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 118, in get
    context = {"name":single_goods.name_en,
AttributeError: 'QuerySet' object has no attribute 'name_en'
ERROR 2019-12-14 16:25:45,644 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 82111
ERROR 2019-12-14 16:25:58,406 exception 135 Internal Server Error: /online/goods/1/detail/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\goods\views.py", line 117, in get
    context = single_goods.values("name_en","image","price","sale","detail_en","description_en")
AttributeError: 'Goods' object has no attribute 'values'
ERROR 2019-12-14 16:25:58,542 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 500 81829
INFO 2019-12-14 16:26:11,223 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 126
INFO 2019-12-14 16:27:55,396 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 150
INFO 2019-12-14 16:29:07,036 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 149
INFO 2019-12-14 16:29:39,989 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
WARNING 2019-12-14 16:29:40,050 base 152 Not Found: /favicon.ico
WARNING 2019-12-14 16:29:40,051 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2531
INFO 2019-12-14 16:29:46,617 basehttp 124 "GET /online/goods/1/detail/ HTTP/1.1" 200 147
WARNING 2019-12-14 20:39:37,307 base 152 Not Found: /online/carts/
WARNING 2019-12-14 20:39:37,308 basehttp 124 "GET /online/carts/ HTTP/1.1" 404 3784
ERROR 2019-12-14 20:40:13,969 exception 135 Internal Server Error: /online/carts/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 27, in get
    return JsonResponse(context)
  File "D:\python_virtual\django_env\lib\site-packages\django\http\response.py", line 524, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
ERROR 2019-12-14 20:40:14,098 basehttp 124 "GET /online/carts/ HTTP/1.1" 500 100255
INFO 2019-12-14 20:40:33,777 basehttp 124 "GET /online/carts/ HTTP/1.1" 200 159
ERROR 2019-12-14 20:43:42,843 exception 135 Internal Server Error: /online/carts/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 29, in get
    sum += cart.goods.price * cart.quantity
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
ERROR 2019-12-14 20:43:42,942 basehttp 124 "GET /online/carts/ HTTP/1.1" 500 95158
INFO 2019-12-14 20:44:43,239 basehttp 124 "GET /online/carts/ HTTP/1.1" 200 185
INFO 2019-12-14 21:02:20,642 basehttp 124 "GET /online/carts/ HTTP/1.1" 200 247
ERROR 2019-12-14 21:05:30,159 exception 135 Internal Server Error: /online/cart/1/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 70, in put
    data = json.loads(request.body.decode())
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 1 (char 21)
ERROR 2019-12-14 21:05:30,385 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 500 107279
ERROR 2019-12-14 21:06:19,879 exception 135 Internal Server Error: /online/cart/1/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 70, in put
    data = json.loads(request.body.decode())
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 1 (char 20)
ERROR 2019-12-14 21:06:19,931 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 500 107273
ERROR 2019-12-14 21:06:33,713 exception 135 Internal Server Error: /online/cart/1/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 70, in put
    data = json.loads(request.body.decode())
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 1 (char 22)
ERROR 2019-12-14 21:06:33,767 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 500 107309
ERROR 2019-12-14 21:07:34,680 exception 135 Internal Server Error: /online/cart/1/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\cart\views.py", line 70, in put
    data = json.loads(request.body.decode())
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 1 (char 22)
ERROR 2019-12-14 21:07:34,883 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 500 109495
INFO 2019-12-14 21:07:41,013 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:08:23,698 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:09:16,997 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:09:56,698 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:11:43,012 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:12:08,797 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:12:30,014 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:12:30,715 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:14:18,645 basehttp 124 "PUT /online/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-14 21:14:50,839 basehttp 124 "PUT /online/cart/2/ HTTP/1.1" 200 44
ERROR 2019-12-14 22:20:41,697 exception 135 Internal Server Error: /online/order/settlement/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\order\views.py", line 30, in post
    if user.address[0]:
TypeError: 'RelatedManager' object does not support indexing
ERROR 2019-12-14 22:20:41,800 basehttp 124 "POST /online/order/settlement/ HTTP/1.1" 500 96313
ERROR 2019-12-14 22:21:05,011 exception 135 Internal Server Error: /online/order/settlement/
Traceback (most recent call last):
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_virtual\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\zyt\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "D:\python_virtual\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\zyt\Desktop\weigan_shopping\online\order\views.py", line 32, in post
    address = {"name":address.name,"road":address.road,"district":address.district,"city":address.city,"province":address.province,"postcode":address.postcode,"phone_number":address.phone}
AttributeError: 'RelatedManager' object has no attribute 'road'
ERROR 2019-12-14 22:21:05,112 basehttp 124 "POST /online/order/settlement/ HTTP/1.1" 500 96771
INFO 2019-12-14 22:22:31,929 basehttp 124 "POST /online/order/settlement/ HTTP/1.1" 200 468
WARNING 2019-12-17 11:21:21,354 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-17 11:21:21,357 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 2432
WARNING 2019-12-17 11:22:54,435 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-17 11:22:54,437 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 2426
WARNING 2019-12-17 11:23:26,979 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-17 11:23:26,986 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 2426
WARNING 2019-12-17 11:23:27,190 base 152 Not Found: /favicon.ico
WARNING 2019-12-17 11:23:27,193 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2417
ERROR 2019-12-17 11:23:49,013 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 59, in get
    goods.append({"id": single_goods.id, "name": single_goods.name_en, "price": single_goods.price,
AttributeError: 'QuerySet' object has no attribute 'append'
ERROR 2019-12-17 11:23:49,532 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80480
ERROR 2019-12-17 11:25:13,158 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 59, in get
    goods_list = [{"id": goods.id, "name": goods.name_en, "price": goods.price,
AttributeError: 'QuerySet' object has no attribute 'id'
ERROR 2019-12-17 11:25:13,279 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80430
ERROR 2019-12-17 11:25:14,037 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 59, in get
    goods_list = [{"id": goods.id, "name": goods.name_en, "price": goods.price,
AttributeError: 'QuerySet' object has no attribute 'id'
ERROR 2019-12-17 11:25:14,080 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80430
ERROR 2019-12-17 11:25:14,718 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 59, in get
    goods_list = [{"id": goods.id, "name": goods.name_en, "price": goods.price,
AttributeError: 'QuerySet' object has no attribute 'id'
ERROR 2019-12-17 11:25:14,768 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80430
ERROR 2019-12-17 11:25:15,522 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 59, in get
    goods_list = [{"id": goods.id, "name": goods.name_en, "price": goods.price,
AttributeError: 'QuerySet' object has no attribute 'id'
ERROR 2019-12-17 11:25:15,565 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80430
ERROR 2019-12-17 11:25:52,225 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 62, in get
    for single_goods in goods:
TypeError: 'Goods' object is not iterable
ERROR 2019-12-17 11:25:52,349 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80279
ERROR 2019-12-17 11:26:20,277 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 62, in get
    for single_goods in goods:
TypeError: 'Goods' object is not iterable
ERROR 2019-12-17 11:26:20,437 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 80161
ERROR 2019-12-17 11:26:51,997 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:26:52,133 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108245
ERROR 2019-12-17 11:27:13,454 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:27:13,640 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108265
ERROR 2019-12-17 11:27:35,224 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:27:35,385 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108269
ERROR 2019-12-17 11:27:37,499 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:27:37,556 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108269
ERROR 2019-12-17 11:27:38,498 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:27:38,557 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108269
ERROR 2019-12-17 11:27:38,818 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 67, in get
    return JsonResponse({"errcode":"0","result":result})
  File "F:\Env\django_env\lib\site-packages\django\http\response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\Env\django_env\lib\site-packages\django\core\serializers\json.py", line 121, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "d:\program files (x86)\python\Lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR 2019-12-17 11:27:38,880 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 108269
INFO 2019-12-17 11:28:34,649 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 159
INFO 2019-12-17 11:30:30,561 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 266
INFO 2019-12-17 11:30:40,876 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 266
WARNING 2019-12-17 11:35:04,248 base 152 Not Found: /api/goods/new/
WARNING 2019-12-17 11:35:04,251 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 404 3174
ERROR 2019-12-17 11:35:20,607 exception 135 Internal Server Error: /api/goods/new/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 89, in get
    goods.append({"id": single_goods.id, "name": single_goods.name_en, "price": single_goods.price,
AttributeError: 'QuerySet' object has no attribute 'append'
ERROR 2019-12-17 11:35:20,718 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 500 79940
INFO 2019-12-17 11:35:35,957 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 266
INFO 2019-12-17 11:41:06,268 basehttp 124 "GET /api/goods/category/2 HTTP/1.1" 301 0
ERROR 2019-12-17 11:41:06,302 exception 135 Internal Server Error: /api/goods/category/2/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 113, in get
    for single_goods in goods:
TypeError: 'Goods' object is not iterable
ERROR 2019-12-17 11:41:06,416 basehttp 124 "GET /api/goods/category/2/ HTTP/1.1" 500 80336
INFO 2019-12-17 11:41:22,854 basehttp 124 "GET /api/goods/category/2 HTTP/1.1" 301 0
INFO 2019-12-17 11:41:22,904 basehttp 124 "GET /api/goods/category/2/ HTTP/1.1" 200 146
WARNING 2019-12-17 11:43:36,533 base 152 Not Found: /api/goods/1/
WARNING 2019-12-17 11:43:36,535 basehttp 124 "GET /api/goods/1/ HTTP/1.1" 404 3189
INFO 2019-12-17 11:43:52,713 basehttp 124 "GET /api/goods/1/ HTTP/1.1" 200 160
INFO 2019-12-17 11:47:08,928 basehttp 124 "GET /api/goods/ HTTP/1.1" 200 16
INFO 2019-12-17 13:51:28,778 basehttp 124 "GET /api/goods/1/ HTTP/1.1" 200 160
INFO 2019-12-17 13:56:36,809 basehttp 124 "GET /api/goods/search/?keyword=cook HTTP/1.1" 200 159
INFO 2019-12-17 14:02:31,015 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 266
ERROR 2019-12-17 14:19:13,715 exception 135 Internal Server Error: /account/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\account\views.py", line 54, in get
    context.update(useraddress[0])
IndexError: list index out of range
ERROR 2019-12-17 14:19:13,862 basehttp 124 "GET /account/ HTTP/1.1" 500 92176
ERROR 2019-12-17 14:20:30,131 exception 135 Internal Server Error: /account/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\account\views.py", line 55, in get
    context.update(useraddress[0])
IndexError: list index out of range
ERROR 2019-12-17 14:20:30,277 basehttp 124 "GET /account/ HTTP/1.1" 500 92217
ERROR 2019-12-17 14:23:14,959 exception 135 Internal Server Error: /account/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\account\views.py", line 55, in get
    context.update(useraddress[0])
IndexError: list index out of range
ERROR 2019-12-17 14:23:15,182 basehttp 124 "GET /account/ HTTP/1.1" 500 94106
INFO 2019-12-17 14:25:06,634 basehttp 124 "GET /account/ HTTP/1.1" 200 82
INFO 2019-12-17 14:26:08,919 basehttp 124 "GET /account/ HTTP/1.1" 200 230
INFO 2019-12-17 14:29:01,196 basehttp 124 "GET /account/ HTTP/1.1" 200 259
ERROR 2019-12-17 14:30:31,115 exception 135 Internal Server Error: /account/login/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\account\views.py", line 34, in post
    if not user.check_password(password):
AttributeError: 'QuerySet' object has no attribute 'check_password'
ERROR 2019-12-17 14:30:31,258 basehttp 124 "POST /account/login/ HTTP/1.1" 500 79675
INFO 2019-12-17 14:31:24,902 basehttp 124 "POST /account/login/ HTTP/1.1" 200 46
INFO 2019-12-17 14:34:53,257 basehttp 124 "GET /account/ HTTP/1.1" 200 259
INFO 2019-12-17 14:36:01,615 basehttp 124 "PUT /account/ HTTP/1.1" 200 52
ERROR 2019-12-17 14:36:50,214 exception 135 Internal Server Error: /account/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\utils\decorator.py", line 21, in wrapper
    return func(request,user,*args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\account\views.py", line 64, in put
    data = json.loads(request.body.decode())
  File "d:\program files (x86)\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\program files (x86)\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 5 (char 132)
ERROR 2019-12-17 14:36:50,372 basehttp 124 "PUT /account/ HTTP/1.1" 500 106355
INFO 2019-12-17 14:37:09,459 basehttp 124 "PUT /account/ HTTP/1.1" 200 40
INFO 2019-12-17 14:43:00,742 basehttp 124 "PUT /account/ HTTP/1.1" 200 42
INFO 2019-12-17 14:46:25,170 basehttp 124 "PUT /account/ HTTP/1.1" 200 42
INFO 2019-12-17 14:48:56,153 basehttp 124 "GET /account/ HTTP/1.1" 200 342
INFO 2019-12-17 14:49:22,101 basehttp 124 "PUT /account/ HTTP/1.1" 200 42
INFO 2019-12-17 14:50:49,520 basehttp 124 "POST /api/account/login/ HTTP/1.1" 200 46
INFO 2019-12-17 14:50:58,382 basehttp 124 "POST /api/account/login/ HTTP/1.1" 200 46
INFO 2019-12-17 14:51:35,899 basehttp 124 "POST /api/account/login/ HTTP/1.1" 200 46
INFO 2019-12-17 14:51:54,543 basehttp 124 "POST /api/account/login/ HTTP/1.1" 200 46
INFO 2019-12-17 14:52:32,303 basehttp 124 "POST /api/account/login/ HTTP/1.1" 200 43
INFO 2019-12-17 14:55:36,736 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 52
INFO 2019-12-17 14:55:41,525 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:56:10,826 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:56:28,271 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:56:36,458 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:57:09,478 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:57:37,460 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:58:00,687 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:58:12,762 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 14:59:29,753 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 15:00:03,467 basehttp 124 "GET /account/ HTTP/1.1" 200 342
INFO 2019-12-17 15:01:24,345 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 15:02:23,738 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 40
INFO 2019-12-17 15:02:51,434 basehttp 124 "POST /api/account/signup/ HTTP/1.1" 200 45
WARNING 2019-12-17 15:04:19,863 base 152 Not Found: /api/account/logout/
WARNING 2019-12-17 15:04:19,865 basehttp 124 "GET /api/account/logout/ HTTP/1.1" 404 4182
WARNING 2019-12-17 15:04:35,915 base 152 Not Found: /api/account/logout/
WARNING 2019-12-17 15:04:35,917 basehttp 124 "GET /api/account/logout/ HTTP/1.1" 404 4186
INFO 2019-12-17 15:04:57,619 basehttp 124 "GET /api/account/logout/ HTTP/1.1" 200 44
INFO 2019-12-17 15:10:51,455 basehttp 124 "GET /carts/ HTTP/1.1" 200 145
INFO 2019-12-17 15:16:50,788 basehttp 124 "POST /carts/ HTTP/1.1" 200 40
INFO 2019-12-17 15:17:30,301 basehttp 124 "POST /carts/ HTTP/1.1" 200 40
INFO 2019-12-17 15:21:00,344 basehttp 124 "POST /carts/ HTTP/1.1" 200 49
INFO 2019-12-17 15:21:21,658 basehttp 124 "POST /carts/ HTTP/1.1" 200 49
INFO 2019-12-17 15:22:28,562 basehttp 124 "GET /carts/ HTTP/1.1" 200 275
INFO 2019-12-17 15:24:32,990 basehttp 124 "POST /carts/ HTTP/1.1" 200 49
ERROR 2019-12-17 15:38:58,629 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:38:58,743 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:39:38,000 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:39:38,113 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:41:10,736 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:41:10,832 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:48:14,546 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:48:14,656 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:48:45,119 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:48:45,250 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:49:23,786 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:49:23,897 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:49:46,098 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:49:46,247 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:49:48,448 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:49:48,498 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
ERROR 2019-12-17 15:51:21,867 exception 135 Internal Server Error: /make/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: make() takes 0 positional arguments but 1 was given
ERROR 2019-12-17 15:51:21,972 basehttp 124 "GET /make/ HTTP/1.1" 500 65439
INFO 2019-12-17 15:51:37,305 basehttp 124 "GET /make/ HTTP/1.1" 200 2
INFO 2019-12-17 15:51:49,101 basehttp 124 "GET /make/ HTTP/1.1" 200 2
INFO 2019-12-17 15:53:51,486 basehttp 124 "GET /make/ HTTP/1.1" 200 2
INFO 2019-12-17 16:10:57,530 basehttp 124 "POST /api/carts/ HTTP/1.1" 200 49
INFO 2019-12-17 16:11:59,873 basehttp 124 "PUT /api/cart/1/ HTTP/1.1" 200 44
INFO 2019-12-17 16:13:59,443 basehttp 124 "DELETE /api/cart/1/ HTTP/1.1" 200 44
ERROR 2019-12-17 17:19:48,783 exception 135 Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 48, in index
    goods.append({"id":single_goods.id,"name":single_goods.name_en,"price":single_goods.price,"is_hot":single_goods.is_hot,"image":single_goods.image})
AttributeError: 'QuerySet' object has no attribute 'append'
ERROR 2019-12-17 17:19:48,898 basehttp 124 "GET /index/ HTTP/1.1" 500 71104
ERROR 2019-12-17 17:20:13,925 exception 135 Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 51, in index
    goods.append({"id":single_goods.id,"name":single_goods.name_en,"price":single_goods.price,"is_hot":single_goods.is_hot,"image":single_goods.image})
AttributeError: 'QuerySet' object has no attribute 'append'
ERROR 2019-12-17 17:20:14,053 basehttp 124 "GET /index/ HTTP/1.1" 500 71028
ERROR 2019-12-17 17:21:50,807 exception 135 Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 53, in index
    goods.append({"id":single_goods.id,"name":single_goods.name_en,"price":single_goods.price,"is_hot":single_goods.is_hot,"image":settings.URL_PREFIX + single_goods.image.url})
AttributeError: 'QuerySet' object has no attribute 'append'
ERROR 2019-12-17 17:21:50,921 basehttp 124 "GET /index/ HTTP/1.1" 500 71273
INFO 2019-12-17 17:22:07,984 basehttp 124 "GET /index/ HTTP/1.1" 200 6269
INFO 2019-12-17 17:23:11,157 basehttp 124 "GET /index/ HTTP/1.1" 200 6269
INFO 2019-12-17 17:34:40,717 basehttp 124 "GET /index/ HTTP/1.1" 200 6823
INFO 2019-12-17 17:34:40,799 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-17 17:34:40,801 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-17 17:34:40,801 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-17 17:34:40,802 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-17 17:34:40,811 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-17 17:34:40,829 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:34:40,830 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:34:40,979 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-17 17:34:47,786 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:34:47,788 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:34:47,822 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:35:24,238 basehttp 124 "GET /index/ HTTP/1.1" 200 6823
WARNING 2019-12-17 17:35:24,410 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:35:24,412 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
WARNING 2019-12-17 17:35:24,570 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:35:24,576 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:36:42,606 basehttp 124 "GET /index/ HTTP/1.1" 200 6823
INFO 2019-12-17 17:36:42,674 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
WARNING 2019-12-17 17:36:42,761 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:36:42,764 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
WARNING 2019-12-17 17:36:42,851 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:36:42,854 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:36:43,044 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:39:17,270 basehttp 124 "GET /index/ HTTP/1.1" 200 6823
WARNING 2019-12-17 17:39:17,312 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:39:17,315 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:39:17,515 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:39:20,911 basehttp 124 "GET /index/ HTTP/1.1" 200 6823
WARNING 2019-12-17 17:39:20,962 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:39:20,965 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:39:21,136 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:40:49,008 basehttp 124 "GET /index/ HTTP/1.1" 200 6817
WARNING 2019-12-17 17:40:49,043 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:40:49,048 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:40:49,243 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:41:13,698 basehttp 124 "GET /index/ HTTP/1.1" 200 6779
INFO 2019-12-17 17:41:13,774 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 304 0
INFO 2019-12-17 17:41:13,778 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 304 0
INFO 2019-12-17 17:41:13,781 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 304 0
INFO 2019-12-17 17:41:13,782 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 304 0
INFO 2019-12-17 17:41:13,783 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 304 0
INFO 2019-12-17 17:41:13,785 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 304 0
WARNING 2019-12-17 17:41:13,820 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:41:13,824 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
WARNING 2019-12-17 17:41:13,968 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:41:13,970 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:41:14,124 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:41:35,509 basehttp 124 "GET /index/ HTTP/1.1" 200 6780
WARNING 2019-12-17 17:41:35,562 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:41:35,565 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:41:35,782 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:41:37,676 basehttp 124 "GET /index/ HTTP/1.1" 200 6780
WARNING 2019-12-17 17:41:37,719 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:41:37,722 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:41:37,764 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:41:38,670 basehttp 124 "GET /index/ HTTP/1.1" 200 6780
WARNING 2019-12-17 17:41:38,712 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:41:38,719 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:41:38,896 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-17 17:43:28,088 basehttp 124 "GET /index/ HTTP/1.1" 200 6780
WARNING 2019-12-17 17:43:28,310 base 152 Not Found: /index/<script
WARNING 2019-12-17 17:43:28,313 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-17 17:43:28,532 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
ERROR 2019-12-17 17:56:06,537 exception 135 Internal Server Error: /api/goods/hot/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 97, in get
    result = t.render(context=result)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 203, in render
    with context.render_context.push_state(self):
AttributeError: 'dict' object has no attribute 'render_context'
ERROR 2019-12-17 17:56:06,672 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 500 84987
INFO 2019-12-17 17:57:32,334 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 1378
INFO 2019-12-17 18:02:11,265 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1602
INFO 2019-12-17 18:03:20,359 basehttp 124 "GET /api/goods/new/?count=6 HTTP/1.1" 200 1602
INFO 2019-12-17 18:03:28,943 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1602
WARNING 2019-12-17 18:03:29,183 base 152 Not Found: /favicon.ico
WARNING 2019-12-17 18:03:29,185 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 4823
INFO 2019-12-17 18:03:30,824 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 1378
INFO 2019-12-17 18:03:34,904 basehttp 124 "GET /api/goods/hot/?count=6 HTTP/1.1" 200 1378
INFO 2019-12-17 18:03:40,198 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1602
INFO 2019-12-17 18:04:56,125 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:08:03,885 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 1378
INFO 2019-12-17 18:09:04,304 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:10:32,823 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:10:59,136 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:10:59,283 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:11:04,775 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:11:10,790 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:11:40,121 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:12:10,291 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:12:18,224 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:14:10,283 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:16:12,960 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:16:29,200 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:16:43,324 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:17:51,545 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:20:48,542 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:34,451 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,456 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,465 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,466 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,474 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,475 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,481 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:41,486 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:22:46,137 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:24:28,609 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:24:36,390 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:25:17,539 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:25:38,618 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 40
INFO 2019-12-17 18:27:32,116 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 0
INFO 2019-12-18 08:49:49,718 basehttp 124 "GET /index/ HTTP/1.1" 200 6812
INFO 2019-12-18 08:49:49,787 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 304 0
INFO 2019-12-18 08:49:49,790 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 304 0
INFO 2019-12-18 08:49:49,790 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 304 0
INFO 2019-12-18 08:49:49,790 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 304 0
INFO 2019-12-18 08:49:49,791 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 304 0
INFO 2019-12-18 08:49:49,793 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 304 0
WARNING 2019-12-18 08:49:49,813 base 152 Not Found: /index/<script
WARNING 2019-12-18 08:49:49,814 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
INFO 2019-12-18 08:49:52,440 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
WARNING 2019-12-18 08:49:54,555 base 152 Not Found: /goods/
WARNING 2019-12-18 08:49:54,557 basehttp 124 "GET /goods/ HTTP/1.1" 404 4805
WARNING 2019-12-18 08:49:54,642 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 08:49:54,644 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 4820
WARNING 2019-12-18 08:50:00,891 base 152 Not Found: /api/goods/
WARNING 2019-12-18 08:50:00,892 basehttp 124 "GET /api/goods/ HTTP/1.1" 404 4817
INFO 2019-12-18 08:50:01,042 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
WARNING 2019-12-18 08:50:01,093 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 08:50:01,093 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 4823
INFO 2019-12-18 08:58:17,790 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 0
INFO 2019-12-18 09:09:36,455 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
INFO 2019-12-18 09:13:06,083 basehttp 124 "GET /index/ HTTP/1.1" 200 6812
WARNING 2019-12-18 09:13:06,126 base 152 Not Found: /index/<script
WARNING 2019-12-18 09:13:06,129 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
WARNING 2019-12-18 09:13:06,446 base 152 Not Found: /index/<script
WARNING 2019-12-18 09:13:06,449 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 4834
WARNING 2019-12-18 09:35:48,657 base 152 Not Found: /template/index.html
WARNING 2019-12-18 09:35:48,659 basehttp 124 "GET /template/index.html HTTP/1.1" 404 5036
WARNING 2019-12-18 09:35:59,688 base 152 Not Found: /templates/index.html
WARNING 2019-12-18 09:35:59,690 basehttp 124 "GET /templates/index.html HTTP/1.1" 404 5039
INFO 2019-12-18 09:41:38,851 basehttp 124 "GET /account/signup/ HTTP/1.1" 200 6768
WARNING 2019-12-18 09:41:38,886 base 152 Not Found: /account/assets/images/icon.png
WARNING 2019-12-18 09:41:38,888 basehttp 124 "GET /account/assets/images/icon.png HTTP/1.1" 404 5236
WARNING 2019-12-18 09:41:38,892 base 152 Not Found: /account/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-18 09:41:38,894 basehttp 124 "GET /account/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 5284
WARNING 2019-12-18 09:41:38,905 base 152 Not Found: /account/assets/javascript/common/base.js
WARNING 2019-12-18 09:41:38,911 base 152 Not Found: /account/assets/javascript/common/header.js
WARNING 2019-12-18 09:41:38,913 basehttp 124 "GET /account/assets/javascript/common/base.js HTTP/1.1" 404 5266
WARNING 2019-12-18 09:41:38,914 basehttp 124 "GET /account/assets/javascript/common/header.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:38,929 base 152 Not Found: /account/assets/javascript/common/common.js
WARNING 2019-12-18 09:41:38,934 base 152 Not Found: /account/assets/javascript/page/register.js
WARNING 2019-12-18 09:41:38,937 basehttp 124 "GET /account/assets/javascript/common/common.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:38,938 basehttp 124 "GET /account/assets/javascript/page/register.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:39,765 base 152 Not Found: /account/assets/css/page/register.less
WARNING 2019-12-18 09:41:39,772 base 152 Not Found: /account/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-18 09:41:39,773 basehttp 124 "GET /account/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 5284
WARNING 2019-12-18 09:41:39,774 basehttp 124 "GET /account/assets/css/page/register.less HTTP/1.1" 404 5257
WARNING 2019-12-18 09:41:39,785 base 152 Not Found: /account/assets/javascript/common/base.js
WARNING 2019-12-18 09:41:39,786 basehttp 124 "GET /account/assets/javascript/common/base.js HTTP/1.1" 404 5266
WARNING 2019-12-18 09:41:39,798 base 152 Not Found: /account/assets/javascript/common/header.js
WARNING 2019-12-18 09:41:39,800 basehttp 124 "GET /account/assets/javascript/common/header.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:39,840 base 152 Not Found: /account/assets/javascript/common/common.js
WARNING 2019-12-18 09:41:39,843 basehttp 124 "GET /account/assets/javascript/common/common.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:39,855 base 152 Not Found: /account/assets/javascript/page/register.js
WARNING 2019-12-18 09:41:39,858 basehttp 124 "GET /account/assets/javascript/page/register.js HTTP/1.1" 404 5272
WARNING 2019-12-18 09:41:39,887 base 152 Not Found: /account/assets/images/icon/loveFamily.ico
WARNING 2019-12-18 09:41:39,888 basehttp 124 "GET /account/assets/images/icon/loveFamily.ico HTTP/1.1" 404 5269
INFO 2019-12-18 09:43:57,826 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
ERROR 2019-12-18 10:25:22,812 exception 135 Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 56, in index
    return render(request,"index.html",context=context)
  File "F:\Env\django_env\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\Env\django_env\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\Env\django_env\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\Env\django_env\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\Env\django_env\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\Env\django_env\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\Env\django_env\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\defaulttags.py", line 827, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 40: 'endfor'. Did you forget to register or load this tag?
ERROR 2019-12-18 10:25:23,031 basehttp 124 "GET /index/ HTTP/1.1" 500 196919
ERROR 2019-12-18 10:29:13,514 exception 135 Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 56, in index
    return render(request,"index.html",context=context)
  File "F:\Env\django_env\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\Env\django_env\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\Env\django_env\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\Env\django_env\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\Env\django_env\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\Env\django_env\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\Env\django_env\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "F:\Env\django_env\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\Env\django_env\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 44: 'endblock'. Did you forget to register or load this tag?
ERROR 2019-12-18 10:29:13,611 basehttp 124 "GET /index/ HTTP/1.1" 500 180886
INFO 2019-12-18 10:39:48,631 basehttp 124 "GET /index/ HTTP/1.1" 200 6545
INFO 2019-12-18 10:39:48,663 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 304 0
INFO 2019-12-18 10:39:48,668 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 304 0
INFO 2019-12-18 10:39:48,669 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 304 0
INFO 2019-12-18 10:39:48,675 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 304 0
INFO 2019-12-18 10:39:48,676 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 304 0
INFO 2019-12-18 10:39:48,677 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 304 0
WARNING 2019-12-18 10:39:48,692 base 152 Not Found: /index/<script
WARNING 2019-12-18 10:39:48,696 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 10:39:48,767 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 11:17:37,584 basehttp 124 "GET /index/ HTTP/1.1" 200 7909
WARNING 2019-12-18 11:17:37,623 base 152 Not Found: /index/<script
INFO 2019-12-18 11:17:37,623 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 35
WARNING 2019-12-18 11:17:37,625 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:17:37,653 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:17:37,654 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:17:37,691 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
WARNING 2019-12-18 11:18:08,185 base 152 Not Found: /goods/2/
WARNING 2019-12-18 11:18:08,188 basehttp 124 "GET /goods/2/ HTTP/1.1" 404 5170
INFO 2019-12-18 11:24:02,534 basehttp 124 "GET /index/ HTTP/1.1" 200 7996
WARNING 2019-12-18 11:24:02,646 base 152 Not Found: /index/<script
INFO 2019-12-18 11:24:02,646 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 43
WARNING 2019-12-18 11:24:02,649 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:24:02,783 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:24:02,785 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:24:02,876 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 11:24:27,884 basehttp 124 "GET /index/ HTTP/1.1" 200 7906
INFO 2019-12-18 11:24:27,932 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:24:27,936 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:24:27,959 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:24:27,962 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:24:27,965 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:24:27,969 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-18 11:24:27,981 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 43
WARNING 2019-12-18 11:24:28,027 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:24:28,030 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:24:28,420 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
INFO 2019-12-18 11:24:28,438 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 11:26:12,979 basehttp 124 "GET /index/ HTTP/1.1" 200 7903
INFO 2019-12-18 11:26:13,016 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:26:13,024 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:26:13,031 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:26:13,031 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:26:13,032 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:26:13,038 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-18 11:26:13,052 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
WARNING 2019-12-18 11:26:13,092 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:26:13,094 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:26:13,128 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:26:13,132 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:26:13,341 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
INFO 2019-12-18 11:26:13,366 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 11:27:21,125 basehttp 124 "GET /index/ HTTP/1.1" 200 7996
INFO 2019-12-18 11:27:21,165 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:27:21,166 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:27:21,228 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:27:21,229 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:27:21,234 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
INFO 2019-12-18 11:27:21,252 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 11:27:21,267 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:27:21,269 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:27:21,286 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
WARNING 2019-12-18 11:27:21,387 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:27:21,390 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:27:21,729 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
INFO 2019-12-18 11:27:21,753 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 11:29:45,147 basehttp 124 "GET /index/ HTTP/1.1" 200 7914
WARNING 2019-12-18 11:29:45,239 base 152 Not Found: /index/<script
INFO 2019-12-18 11:29:45,239 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 304 0
WARNING 2019-12-18 11:29:45,242 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:29:45,397 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:29:45,405 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:29:45,484 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:30:07,219 basehttp 124 "GET /index/ HTTP/1.1" 200 7920
INFO 2019-12-18 11:30:07,301 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:30:07,314 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:30:07,318 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:30:07,320 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:30:07,326 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:30:07,340 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
INFO 2019-12-18 11:30:07,341 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 11:30:07,359 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:30:07,361 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:30:07,537 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:30:07,542 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:30:07,811 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 11:30:07,830 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:44:15,177 basehttp 124 "GET /index/ HTTP/1.1" 200 7914
INFO 2019-12-18 11:44:15,222 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:44:15,234 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:44:15,236 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:44:15,238 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:44:15,240 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:44:15,273 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-18 11:44:15,309 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 56
WARNING 2019-12-18 11:44:15,319 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:44:15,327 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:44:19,940 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:44:19,943 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:44:20,042 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 11:44:20,077 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:49:35,588 basehttp 124 "GET /index/ HTTP/1.1" 200 7940
INFO 2019-12-18 11:49:35,681 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:49:35,702 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:49:35,715 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:49:35,719 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:49:35,732 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 11:49:35,747 base 152 Not Found: /index/<script
INFO 2019-12-18 11:49:35,749 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
WARNING 2019-12-18 11:49:35,749 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:49:35,756 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:49:35,812 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 11:49:35,881 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:49:35,885 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:49:35,954 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:49:51,970 basehttp 124 "GET /index/ HTTP/1.1" 200 7941
INFO 2019-12-18 11:49:52,001 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:49:52,007 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:49:52,034 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:49:52,037 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:49:52,055 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
WARNING 2019-12-18 11:49:52,074 base 152 Not Found: /index/<script
INFO 2019-12-18 11:49:52,075 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
WARNING 2019-12-18 11:49:52,089 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:49:52,092 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 11:49:52,146 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:49:52,147 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:49:52,325 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 11:49:52,360 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:49:53,438 basehttp 124 "GET /index/ HTTP/1.1" 200 7941
INFO 2019-12-18 11:49:53,479 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 11:49:53,488 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 11:49:53,493 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 11:49:53,498 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 11:49:53,500 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 11:49:53,504 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-18 11:49:53,524 basehttp 124 "GET /static/assets/javascript/host.js HTTP/1.1" 200 42
WARNING 2019-12-18 11:49:53,547 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:49:53,549 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 11:49:53,587 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 11:49:53,620 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 11:50:17,950 basehttp 124 "GET /index/ HTTP/1.1" 200 7936
WARNING 2019-12-18 11:50:18,055 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:50:18,057 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
WARNING 2019-12-18 11:50:18,155 base 152 Not Found: /index/<script
WARNING 2019-12-18 11:50:18,159 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 12:03:16,516 basehttp 124 "GET /index/ HTTP/1.1" 200 4833
INFO 2019-12-18 12:03:16,557 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 12:03:16,566 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 12:03:16,567 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 12:03:16,569 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 12:03:16,593 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 12:03:16,607 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 12:03:16,616 base 152 Not Found: /index/<script
WARNING 2019-12-18 12:03:16,618 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5193
INFO 2019-12-18 12:03:16,873 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 12:03:16,901 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 12:03:20,855 basehttp 124 "GET /account/signup/ HTTP/1.1" 200 6768
WARNING 2019-12-18 12:03:20,901 base 152 Not Found: /account/assets/images/icon.png
WARNING 2019-12-18 12:03:20,908 basehttp 124 "GET /account/assets/images/icon.png HTTP/1.1" 404 5236
WARNING 2019-12-18 12:03:20,915 base 152 Not Found: /account/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-18 12:03:20,918 basehttp 124 "GET /account/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 5284
WARNING 2019-12-18 12:03:20,926 base 152 Not Found: /account/assets/javascript/common/base.js
WARNING 2019-12-18 12:03:20,927 basehttp 124 "GET /account/assets/javascript/common/base.js HTTP/1.1" 404 5266
WARNING 2019-12-18 12:03:20,945 base 152 Not Found: /account/assets/css/page/register.less
WARNING 2019-12-18 12:03:20,952 base 152 Not Found: /account/assets/javascript/common/header.js
WARNING 2019-12-18 12:03:20,960 base 152 Not Found: /account/assets/javascript/common/common.js
WARNING 2019-12-18 12:03:20,962 basehttp 124 "GET /account/assets/css/page/register.less HTTP/1.1" 404 5257
WARNING 2019-12-18 12:03:20,968 base 152 Not Found: /account/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-18 12:03:20,975 basehttp 124 "GET /account/assets/javascript/common/common.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:20,976 base 152 Not Found: /account/assets/javascript/page/register.js
WARNING 2019-12-18 12:03:20,976 basehttp 124 "GET /account/assets/javascript/common/header.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:20,977 basehttp 124 "GET /account/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 5284
WARNING 2019-12-18 12:03:20,978 basehttp 124 "GET /account/assets/javascript/page/register.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:21,001 base 152 Not Found: /account/assets/javascript/common/base.js
WARNING 2019-12-18 12:03:21,006 basehttp 124 "GET /account/assets/javascript/common/base.js HTTP/1.1" 404 5266
WARNING 2019-12-18 12:03:21,038 base 152 Not Found: /account/assets/javascript/common/header.js
WARNING 2019-12-18 12:03:21,040 basehttp 124 "GET /account/assets/javascript/common/header.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:21,058 base 152 Not Found: /account/assets/javascript/common/common.js
WARNING 2019-12-18 12:03:21,062 basehttp 124 "GET /account/assets/javascript/common/common.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:21,079 base 152 Not Found: /account/assets/javascript/page/register.js
WARNING 2019-12-18 12:03:21,082 basehttp 124 "GET /account/assets/javascript/page/register.js HTTP/1.1" 404 5272
WARNING 2019-12-18 12:03:21,122 base 152 Not Found: /account/assets/images/icon/loveFamily.ico
WARNING 2019-12-18 12:03:21,128 basehttp 124 "GET /account/assets/images/icon/loveFamily.ico HTTP/1.1" 404 5269
INFO 2019-12-18 12:03:29,948 basehttp 124 "GET /goods/category/2 HTTP/1.1" 301 0
INFO 2019-12-18 12:03:30,004 basehttp 124 "GET /goods/category/2/ HTTP/1.1" 200 8259
WARNING 2019-12-18 12:03:30,058 base 152 Not Found: /goods/category/assets/css/page/index.css
WARNING 2019-12-18 12:03:30,069 base 152 Not Found: /goods/category/assets/images/icon.png
WARNING 2019-12-18 12:03:30,080 base 152 Not Found: /goods/category/assets/javascript/libs/jquery-1.9.1.js
WARNING 2019-12-18 12:03:30,082 basehttp 124 "GET /goods/category/assets/images/icon.png HTTP/1.1" 404 5257
WARNING 2019-12-18 12:03:30,083 basehttp 124 "GET /goods/category/assets/css/page/index.css HTTP/1.1" 404 5266
WARNING 2019-12-18 12:03:30,083 basehttp 124 "GET /goods/category/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 404 5305
WARNING 2019-12-18 12:03:30,094 base 152 Not Found: /goods/category/assets/javascript/common/base.js
WARNING 2019-12-18 12:03:30,103 base 152 Not Found: /goods/category/assets/images/thing.png
WARNING 2019-12-18 12:03:30,113 base 152 Not Found: /goods/category/assets/javascript/page/index.js
WARNING 2019-12-18 12:03:30,119 base 152 Not Found: /goods/category/assets/javascript/common/header.js
WARNING 2019-12-18 12:03:30,119 basehttp 124 "GET /goods/category/assets/javascript/common/base.js HTTP/1.1" 404 5287
WARNING 2019-12-18 12:03:30,122 basehttp 124 "GET /goods/category/assets/javascript/page/index.js HTTP/1.1" 404 5284
WARNING 2019-12-18 12:03:30,123 basehttp 124 "GET /goods/category/assets/javascript/common/header.js HTTP/1.1" 404 5293
WARNING 2019-12-18 12:03:30,123 basehttp 124 "GET /goods/category/assets/images/thing.png HTTP/1.1" 404 5260
WARNING 2019-12-18 12:03:30,144 base 152 Not Found: /goods/category/assets/javascript/page/index.js
WARNING 2019-12-18 12:03:30,147 basehttp 124 "GET /goods/category/assets/javascript/page/index.js HTTP/1.1" 404 5284
WARNING 2019-12-18 12:03:30,191 base 152 Not Found: /goods/category/assets/images/icon/loveFamily.ico
WARNING 2019-12-18 12:03:30,195 basehttp 124 "GET /goods/category/assets/images/icon/loveFamily.ico HTTP/1.1" 404 5290
WARNING 2019-12-18 12:03:40,038 base 152 Not Found: /goods/2/
WARNING 2019-12-18 12:03:40,040 basehttp 124 "GET /goods/2/ HTTP/1.1" 404 5170
WARNING 2019-12-18 12:03:40,151 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 12:03:40,155 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 5179
WARNING 2019-12-18 12:04:20,450 base 152 Not Found: /goods/2/
WARNING 2019-12-18 12:04:20,452 basehttp 124 "GET /goods/2/ HTTP/1.1" 404 5170
INFO 2019-12-18 12:05:10,481 basehttp 124 "GET /index/ HTTP/1.1" 200 4833
INFO 2019-12-18 12:05:10,526 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 12:05:10,532 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
INFO 2019-12-18 12:05:10,534 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 12:05:10,540 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
INFO 2019-12-18 12:05:10,547 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 12:05:10,554 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
WARNING 2019-12-18 12:05:10,590 base 152 Not Found: /index/<script
WARNING 2019-12-18 12:05:10,593 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
INFO 2019-12-18 12:05:10,711 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 12:05:10,750 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 12:05:11,973 basehttp 124 "GET /goods/2/ HTTP/1.1" 200 141
WARNING 2019-12-18 12:05:12,043 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 12:05:12,046 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 5175
INFO 2019-12-18 13:43:20,610 basehttp 124 "GET /index/ HTTP/1.1" 200 4798
WARNING 2019-12-18 13:43:20,666 base 152 Not Found: /index/<script
WARNING 2019-12-18 13:43:20,668 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
WARNING 2019-12-18 13:43:21,794 base 152 Not Found: /index/<script
WARNING 2019-12-18 13:43:21,795 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
INFO 2019-12-18 13:45:44,154 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:46:47,606 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:47:33,322 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:47:43,541 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:48:07,608 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:48:47,321 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 16
INFO 2019-12-18 13:49:12,625 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 41
INFO 2019-12-18 13:49:27,454 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 41
INFO 2019-12-18 13:49:27,786 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
INFO 2019-12-18 13:49:48,199 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 1704
INFO 2019-12-18 13:50:07,756 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 41
WARNING 2019-12-18 13:50:07,865 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 13:50:07,867 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 5178
INFO 2019-12-18 13:52:12,020 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 41
INFO 2019-12-18 13:52:30,724 basehttp 124 "GET /index/ HTTP/1.1" 200 4798
WARNING 2019-12-18 13:52:30,768 base 152 Not Found: /index/<script
WARNING 2019-12-18 13:52:30,770 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
WARNING 2019-12-18 13:52:30,961 basehttp 124 "GET /static/assets/images/icon/loveFamily.icon HTTP/1.1" 404 1715
INFO 2019-12-18 13:53:43,037 basehttp 124 "GET /index/ HTTP/1.1" 200 4797
INFO 2019-12-18 13:53:43,093 basehttp 124 "GET /static/assets/css/page/index.css HTTP/1.1" 200 14760
INFO 2019-12-18 13:53:43,094 basehttp 124 "GET /static/assets/images/icon.png HTTP/1.1" 200 7011
INFO 2019-12-18 13:53:43,100 basehttp 124 "GET /media/1.jpg HTTP/1.1" 200 11259
INFO 2019-12-18 13:53:43,118 basehttp 124 "GET /static/assets/javascript/libs/jquery-1.9.1.js HTTP/1.1" 200 128159
INFO 2019-12-18 13:53:43,131 basehttp 124 "GET /static/assets/javascript/common/base.js HTTP/1.1" 200 944
WARNING 2019-12-18 13:53:43,214 base 152 Not Found: /index/<script
INFO 2019-12-18 13:53:43,216 basehttp 124 "GET /static/assets/javascript/common/header.js HTTP/1.1" 200 1211
WARNING 2019-12-18 13:53:43,217 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
INFO 2019-12-18 13:53:43,225 basehttp 124 "GET /static/assets/images/banner.png HTTP/1.1" 200 2295905
WARNING 2019-12-18 13:53:43,288 base 152 Not Found: /index/<script
WARNING 2019-12-18 13:53:43,294 basehttp 124 "GET /index/%3Cscript HTTP/1.1" 404 5189
INFO 2019-12-18 13:53:43,466 basehttp 124 "GET /static/assets/images/icon/loveFamily.ico HTTP/1.1" 200 1150
INFO 2019-12-18 13:53:46,359 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 41
INFO 2019-12-18 14:02:52,210 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 30
INFO 2019-12-18 14:03:10,380 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 200 30
INFO 2019-12-18 14:03:59,043 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 1060
INFO 2019-12-18 14:04:39,988 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 1060
WARNING 2019-12-18 14:04:40,117 base 152 Not Found: /favicon.ico
WARNING 2019-12-18 14:04:40,119 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 5175
INFO 2019-12-18 14:05:11,007 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 958
INFO 2019-12-18 14:05:30,310 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 200 0
WARNING 2019-12-18 14:06:54,452 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:06:54,453 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 404 5204
WARNING 2019-12-18 14:07:06,695 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:07:06,696 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 404 5204
WARNING 2019-12-18 14:15:51,310 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:15:51,311 basehttp 124 "GET /api/goods/hot/?callback=jQuery19106572588581776726_1576649754482&current=6 HTTP/1.1" 404 5100
WARNING 2019-12-18 14:20:47,427 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:20:47,428 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 4869
WARNING 2019-12-18 14:21:21,788 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:21:21,792 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 4869
WARNING 2019-12-18 14:22:07,143 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:22:07,144 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 404 4886
WARNING 2019-12-18 14:22:17,902 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:22:17,904 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 404 4879
WARNING 2019-12-18 14:22:31,950 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:22:31,952 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 404 4896
WARNING 2019-12-18 14:22:50,859 base 152 Not Found: /api/goods/hot/
WARNING 2019-12-18 14:22:50,860 basehttp 124 "GET /api/goods/hot/?current=6 HTTP/1.1" 404 4892
INFO 2019-12-18 14:23:29,379 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 958
INFO 2019-12-18 14:23:35,950 basehttp 124 "GET /api/goods/hoghjt/ HTTP/1.1" 200 47
INFO 2019-12-18 14:23:41,246 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 958
INFO 2019-12-18 14:23:45,473 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 958
INFO 2019-12-18 14:25:34,072 basehttp 124 "OPTIONS /api/goods/new/ HTTP/1.1" 200 0
INFO 2019-12-18 14:26:00,745 basehttp 124 "GET /api/goods/hot/?callback=jQuery19103003745764580126_1576650361257&current=6 HTTP/1.1" 200 0
INFO 2019-12-18 14:26:30,194 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 200 0
INFO 2019-12-18 14:26:40,381 basehttp 124 "GET /api/goods/category/1 HTTP/1.1" 301 0
INFO 2019-12-18 14:26:40,393 basehttp 124 "GET /api/goods/category/1/ HTTP/1.1" 200 47
INFO 2019-12-18 14:26:52,958 basehttp 124 "OPTIONS /api/goods/hot/?current=6 HTTP/1.1" 200 0
INFO 2019-12-18 14:27:29,716 basehttp 124 "GET /api/goods/category/1 HTTP/1.1" 301 0
ERROR 2019-12-18 14:27:29,726 exception 135 Internal Server Error: /api/goods/category/1/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 103, in get
    return redirect(reverse("GoodsCategoryTemplateView.as_view()"))
  File "F:\Env\django_env\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "F:\Env\django_env\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'GoodsCategoryTemplateView.as_view()' not found. 'GoodsCategoryTemplateView.as_view()' is not a valid view function or pattern name.
ERROR 2019-12-18 14:27:29,833 basehttp 124 "GET /api/goods/category/1/ HTTP/1.1" 500 91248
INFO 2019-12-18 14:28:36,153 basehttp 124 "GET /api/goods/hot HTTP/1.1" 301 0
INFO 2019-12-18 14:28:36,171 basehttp 124 "GET /api/goods/hot/ HTTP/1.1" 200 958
INFO 2019-12-18 14:28:41,032 basehttp 124 "GET /api/goods/new HTTP/1.1" 301 0
INFO 2019-12-18 14:28:41,068 basehttp 124 "GET /api/goods/new/ HTTP/1.1" 200 958
WARNING 2019-12-18 14:28:45,728 base 152 Not Found: /api/goods/hhh
WARNING 2019-12-18 14:28:45,729 basehttp 124 "GET /api/goods/hhh HTTP/1.1" 404 4887
INFO 2019-12-18 14:28:59,108 basehttp 124 "GET /api/goods/category/1 HTTP/1.1" 301 0
ERROR 2019-12-18 14:28:59,125 exception 135 Internal Server Error: /api/goods/category/1/
Traceback (most recent call last):
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\Env\django_env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\Env\django_env\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\weigan_shopping\online\goods\views.py", line 103, in get
    return redirect(reverse("GoodsCategoryTemplateView.as_view()"))
  File "F:\Env\django_env\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "F:\Env\django_env\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'GoodsCategoryTemplateView.as_view()' not found. 'GoodsCategoryTemplateView.as_view()' is not a valid view function or pattern name.
ERROR 2019-12-18 14:28:59,166 basehttp 124 "GET /api/goods/category/1/ HTTP/1.1" 500 91248
